import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./utilities/AuthProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AuthProvider>
                <body>{children}</body>
            </AuthProvider>
        </html>
    );
}
