"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./utilities/AuthProvider";
import { DatabaseProvider } from "./utilities/databaseContext";
import { SelectedWorkspaceProvider } from "./utilities/WorkspaceContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AuthProvider>
                <DatabaseProvider>
                    <SelectedWorkspaceProvider>
                        <body>{children}</body>
                    </SelectedWorkspaceProvider>
                </DatabaseProvider>
            </AuthProvider>
        </html>
    );
}
